apiVersion: appdynamics.com/v1alpha1
kind: Clusteragent
metadata:
  name: NAME
  namespace: appdynamics
spec:
  account: ACCOUNT
  appName: APP_NAME
  appNameStrategy: manual
  controllerUrl: CONTROLLER_URL
  defaultAppName: DEFULT_APP_NAME
  image: docker.io/appdynamics/cluster-agent:20.5.0
  imageInfo:
    java:
      agentMountPath: /opt/appdynamics
      image: docker.io/appdynamics/java-agent:latest
  instrumentationMethod: Env
  instrumentationRules:
  - appName: APP_NAME
    namespaceRegex: tea-store
  netvizInfo:
    bciEnabled: true
    port: 3892
  nsToInstrumentRegex: appdynamics|turbo|tea-store
  nsToMonitor:
  - appdynamics
  - default
  - turbo
  - tea-store
  resourcesToInstrument:
  - Deployment
  - StatefulSet
  serviceAccountName: appdynamics-cluster-agent
