apiVersion: appdynamics.com/v1alpha1
kind: Clusteragent
metadata:
  name: k8s-cluster-agent
  namespace: appdynamics
spec:
  account: "ACCOUNT"
  appName: "TeaStore"
  controllerUrl: "CONTROLLER"
  image: "docker.io/appdynamics/cluster-agent:20.5.0"
  serviceAccountName: appdynamics-cluster-agent
  nsToMonitor: [appdynamics,default,turbo,tea-store]
  instrumentationMethod: Env
  nsToInstrumentRegex: appdynamics|turbo|tea-store
  appNameStrategy: manual
  defaultAppName: APP_NAME
  instrumentationRules:
    - namespaceRegex: tea-store
      appName: TeaStore
  resourcesToInstrument: [Deployment,StatefulSet]
  imageInfo:
    java:
      image: "docker.io/appdynamics/java-agent:latest"
      agentMountPath: /opt/appdynamics
  netvizInfo:
    bciEnabled: true
    port: 3892