apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: appd-netviz-agent
  namespace: appdynamics
spec:
  selector:
    matchLabels:
      name: appd-netviz-agent
  template:
    metadata:
      name: appd-netviz-agent
      labels:
        name: appd-netviz-agent
    spec:
      hostIPC: true
      hostNetwork: true
      containers:
      - name: appd-netviz-agent
        image: docker.io/appdynamics/machine-agent-netviz:latest
        resources:
          requests:
            memory: "250Mi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "1"
        securityContext:
          capabilities:
            add: ["NET_RAW"]
        ports:
        - containerPort: 3892
          hostPort: 3892